version: '2.1'

services:

  whale:
    build: .

  lb:
    image: nginx:alpine
    container_name: my_loadbalancer
    ports: 
      - "8080:80"
    volumes:
      - ./docker/lb/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/web
    networks:
      - vnet-front
      - vnet-back
    depends_on:
      - php

  php:
    image: php:7.1-fpm-alpine
    env_file:
      - .env
    volumes:
      - ./web:/web
    networks:
      - vnet-back
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=web
      - MYSQL_PASSWORD=passwd
      - MYSQL_DABATASE=app
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - vnet-back

  ping:
    image: busybox
    entrypoint: ["/bin/ping", "-c", "3"]
    command: ["loadbalancer"]
    networks:
      - vnet-front
    links:
      - lb:loadbalancer

volumes:
  data-mysql:
    driver: local

networks: 
  vnet-front:
    driver: bridge
  vnet-back:
    driver: bridge
  